app = "warlok-frontend"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"  # Now relative to root

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

# Make sure your app has an IPv6 address
[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000 